name: motion_platform_interface
description: The platform interface for the Motion plugin.
version: 1.3.3
homepage: https://cendre.me
repository: https://github.com/mrcendre/motion
issue_tracker: https://github.com/mrcendre/motion/issues?q=is%3Aissue+is%3Aopen

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
